### ISSUE TITLE
Error: Cannot find module '../webpack.config.js'

### ISSUE THREAD

**Issue by Hannah-goodridge** [rbutera/greater-gatsby#3]
You seem to be missing the webpack config file from this repo:

I get the following error after installing and running `yarn dev`:

```
ERR! Error: Cannot find module '../webpack.config.js'
ERR! Require stack:
ERR! - /Users/hannahgoodridge/Sites/greater-gatsby/.storybook/webpack.config.js
ERR! - /Users/hannahgoodridge/Sites/greater-gatsby/node_modules/@storybook/core/dist/server/utils/server-require.js
ERR! - /Users/hannahgoodridge/Sites/greater-gatsby/node_modules/@storybook/core/dist/server/common/custom-presets.js
ERR! - /Users/hannahgoodridge/Sites/greater-gatsby/node_modules/@storybook/core/dist/server/config.js
ERR! - /Users/hannahgoodridge/Sites/greater-gatsby/node_modules/@storybook/core/dist/server/build-static.js
ERR! - /Users/hannahgoodridge/Sites/greater-gatsby/node_modules/@storybook/core/server.js
ERR! - /Users/hannahgoodridge/Sites/greater-gatsby/node_modules/@storybook/react/dist/server/index.js
ERR! - /Users/hannahgoodridge/Sites/greater-gatsby/node_modules/@storybook/react/bin/index.js
ERR!     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
ERR!     at Function.Module._load (internal/modules/cjs/loader.js:686:27)
ERR!     at Module.require (internal/modules/cjs/loader.js:848:19)
ERR!     at require (internal/modules/cjs/helpers.js:74:18)
ERR!     at Object.<anonymous> (/Users/hannahgoodridge/Sites/greater-gatsby/.storybook/webpack.config.js:4:16)
ERR!     at Module._compile (internal/modules/cjs/loader.js:955:30)
ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
ERR!     at Module.load (internal/modules/cjs/loader.js:811:32)
ERR!     at Function.Module._load (internal/modules/cjs/loader.js:723:14)
ERR!     at Module.require (internal/modules/cjs/loader.js:848:19)
ERR!     at require (internal/modules/cjs/helpers.js:74:18)
ERR!     at interopRequireDefault (/Users/hannahgoodridge/Sites/greater-gatsby/node_modules/@storybook/core/dist/server/utils/server-require.js:63:18)
ERR!     at serverRequire (/Users/hannahgoodridge/Sites/greater-gatsby/node_modules/@storybook/core/dist/server/utils/server-require.js:103:10)
ERR!     at _default (/Users/hannahgoodridge/Sites/greater-gatsby/node_modules/@storybook/core/dist/server/utils/load-custom-webpack-config.js:16:56)
ERR!     at Object.webpack (/Users/hannahgoodridge/Sites/greater-gatsby/node_modules/@storybook/core/dist/server/preview/custom-webpack-preset.js:44:61)
ERR!     at /Users/hannahgoodridge/Sites/greater-gatsby/node_modules/@storybook/core/dist/server/presets.js:261:72
ERR!  Error: Cannot find module '../webpack.config.js'
ERR! Require stack:
ERR! - /Users/hannahgoodridge/Sites/greater-gatsby/.storybook/webpack.config.js
ERR! - /Users/hannahgoodridge/Sites/greater-gatsby/node_modules/@storybook/core/dist/server/utils/server-require.js
ERR! - /Users/hannahgoodridge/Sites/greater-gatsby/node_modules/@storybook/core/dist/server/common/custom-presets.js
ERR! - /Users/hannahgoodridge/Sites/greater-gatsby/node_modules/@storybook/core/dist/server/config.js
ERR! - /Users/hannahgoodridge/Sites/greater-gatsby/node_modules/@storybook/core/dist/server/build-static.js
ERR! - /Users/hannahgoodridge/Sites/greater-gatsby/node_modules/@storybook/core/server.js
ERR! - /Users/hannahgoodridge/Sites/greater-gatsby/node_modules/@storybook/react/dist/server/index.js
ERR! - /Users/hannahgoodridge/Sites/greater-gatsby/node_modules/@storybook/react/bin/index.js
ERR!     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
ERR!     at Function.Module._load (internal/modules/cjs/loader.js:686:27)
ERR!     at Module.require (internal/modules/cjs/loader.js:848:19)
ERR!     at require (internal/modules/cjs/helpers.js:74:18)
ERR!     at Object.<anonymous> (/Users/hannahgoodridge/Sites/greater-gatsby/.storybook/webpack.config.js:4:16)
ERR!     at Module._compile (internal/modules/cjs/loader.js:955:30)
ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
ERR!     at Module.load (internal/modules/cjs/loader.js:811:32)
ERR!     at Function.Module._load (internal/modules/cjs/loader.js:723:14)
ERR!     at Module.require (internal/modules/cjs/loader.js:848:19)
ERR!     at require (internal/modules/cjs/helpers.js:74:18)
ERR!     at interopRequireDefault (/Users/hannahgoodridge/Sites/greater-gatsby/node_modules/@storybook/core/dist/server/utils/server-require.js:63:18)
ERR!     at serverRequire (/Users/hannahgoodridge/Sites/greater-gatsby/node_modules/@storybook/core/dist/server/utils/server-require.js:103:10)
ERR!     at _default (/Users/hannahgoodridge/Sites/greater-gatsby/node_modules/@storybook/core/dist/server/utils/load-custom-webpack-config.js:16:56)
ERR!     at Object.webpack (/Users/hannahgoodridge/Sites/greater-gatsby/node_modules/@storybook/core/dist/server/preview/custom-webpack-preset.js:44:61)
ERR!     at /Users/hannahgoodridge/Sites/greater-gatsby/node_modules/@storybook/core/dist/server/presets.js:261:72 {
ERR!   stack: "Error: Cannot find module '../webpack.config.js'\n" +
ERR!     'Require stack:\n' +
ERR!     '- /Users/hannahgoodridge/Sites/greater-gatsby/.storybook/webpack.config.js\n' +
ERR!     '- /Users/hannahgoodridge/Sites/greater-gatsby/node_modules/@storybook/core/dist/server/utils/server-require.js\n' +
ERR!     '- /Users/hannahgoodridge/Sites/greater-gatsby/node_modules/@storybook/core/dist/server/common/custom-presets.js\n' +
ERR!     '- /Users/hannahgoodridge/Sites/greater-gatsby/node_modules/@storybook/core/dist/server/config.js\n' +
ERR!     '- /Users/hannahgoodridge/Sites/greater-gatsby/node_modules/@storybook/core/dist/server/build-static.js\n' +
ERR!     '- /Users/hannahgoodridge/Sites/greater-gatsby/node_modules/@storybook/core/server.js\n' +
ERR!     '- /Users/hannahgoodridge/Sites/greater-gatsby/node_modules/@storybook/react/dist/server/index.js\n' +
ERR!     '- /Users/hannahgoodridge/Sites/greater-gatsby/node_modules/@storybook/react/bin/index.js\n' +
ERR!     '    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)\n' +
ERR!     '    at Function.Module._load (internal/modules/cjs/loader.js:686:27)\n' +
ERR!     '    at Module.require (internal/modules/cjs/loader.js:848:19)\n' +
ERR!     '    at require (internal/modules/cjs/helpers.js:74:18)\n' +
ERR!     '    at Object.<anonymous> (/Users/hannahgoodridge/Sites/greater-gatsby/.storybook/webpack.config.js:4:16)\n' +
ERR!     '    at Module._compile (internal/modules/cjs/loader.js:955:30)\n' +
ERR!     '    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)\n' +
ERR!     '    at Module.load (internal/modules/cjs/loader.js:811:32)\n' +
ERR!     '    at Function.Module._load (internal/modules/cjs/loader.js:723:14)\n' +
ERR!     '    at Module.require (internal/modules/cjs/loader.js:848:19)\n' +
ERR!     '    at require (internal/modules/cjs/helpers.js:74:18)\n' +
ERR!     '    at interopRequireDefault (/Users/hannahgoodridge/Sites/greater-gatsby/node_modules/@storybook/core/dist/server/utils/server-require.js:63:18)\n' +
ERR!     '    at serverRequire (/Users/hannahgoodridge/Sites/greater-gatsby/node_modules/@storybook/core/dist/server/utils/server-require.js:103:10)\n' +
ERR!     '    at _default (/Users/hannahgoodridge/Sites/greater-gatsby/node_modules/@storybook/core/dist/server/utils/load-custom-webpack-config.js:16:56)\n' +
ERR!     '    at Object.webpack (/Users/hannahgoodridge/Sites/greater-gatsby/node_modules/@storybook/core/dist/server/preview/custom-webpack-preset.js:44:61)\n' +
ERR!     '    at /Users/hannahgoodridge/Sites/greater-gatsby/node_modules/@storybook/core/dist/server/presets.js:261:72',
ERR!   code: 'MODULE_NOT_FOUND',
ERR!   requireStack: [
ERR!     '/Users/hannahgoodridge/Sites/greater-gatsby/.storybook/webpack.config.js',
ERR!     '/Users/hannahgoodridge/Sites/greater-gatsby/node_modules/@storybook/core/dist/server/utils/server-require.js',
ERR!     '/Users/hannahgoodridge/Sites/greater-gatsby/node_modules/@storybook/core/dist/server/common/custom-presets.js',
ERR!     '/Users/hannahgoodridge/Sites/greater-gatsby/node_modules/@storybook/core/dist/server/config.js',
ERR!     '/Users/hannahgoodridge/Sites/greater-gatsby/node_modules/@storybook/core/dist/server/build-static.js',
ERR!     '/Users/hannahgoodridge/Sites/greater-gatsby/node_modules/@storybook/core/server.js',
ERR!     '/Users/hannahgoodridge/Sites/greater-gatsby/node_modules/@storybook/react/dist/server/index.js',
ERR!     '/Users/hannahgoodridge/Sites/greater-gatsby/node_modules/@storybook/react/bin/index.js'
ERR!   ]
ERR! }

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.
```

**Comment by Hannah-goodridge** [comment]
This is what I wanted to have a peek at to fix one of my issues. :)

**Comment by rbutera** [comment]
🤦️ can't believe I forgot to update that file.

Just updated. Please pull/fetch latest updates and let me know if it works for you.

**Comment by rbutera** [comment]
@Hannah-goodridge 

🤦️ can't believe I forgot to update that file.

Just updated. Please pull/fetch latest updates and let me know if it works for you.

**Comment by Hannah-goodridge** [comment]
No probs, thanks for writing such an in depth article this has really helped me.

**Comment by Hannah-goodridge** [comment]
Ahh it seems you've replaced the wrong file.
(I blame myself for rubbish error messages).
It's the webpack file in the very root of the project you look like you are requiring thats missing.
The storybook .webpack.config was fine. 

aka: `const custom = require('../webpack.config.js')` in .storybook > webpack.config.js

**Comment by rbutera** [comment]
@Hannah-goodridge AFAIK Gatsby projects can't/don't generally use a base webpack.config.js 

If you have a look at the updated .storybook/webpack.config.js you should find all you need. Let me know if it's still broken and I'll have a play around.
